input_text_directory: inputs\text.txt
output_directory: outputs\siren3
image_width: 704
image_height: 384
# title: None
# title_image: inputs/title_img.png
character_descriptions:
  Errol: Dark-haired male captain
image_prefix_prompt: photo of the most beautiful artwork in the world featuring 
image_style_prompt: intricate, trending on artstation, professional majestic oil painting by WLOP, Ross Tran, Greg Rutkowski, Studio Ghibli, Makoto Shinkai and Alphonse Mucha, trending on CGSociety, high detail, dynamic composition, sharp focus, beautiful and detailed lighting, shadows, 100mm
image_negative_prompt: posing, duplicate, disfigured, signature, text, morbid, mutilated, out of frame, extra fingers, mutated hand, mutation, deformed, blurry, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, extra limbs, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, logo, watermark
stable_diffusion_model: C:\Users\jawk\OneDrive\Documents\GitHub\stable-diffusion\stable_diffusion\checkpoints\protogenX34OfficialR_1.ckpt
real_ersgan_executable: C:\Users\jawk\OneDrive\Documents\GitHub\Real-ESRGAN\realesrgan-ncnn-vulkan.exe
gfpgan_model: C:\Users\jawk\OneDrive\Documents\GitHub\stable-diffusion\stable_diffusion\checkpoints\GFPGANv1.4.pth
illustration_kwargs:
  plms: False
  ddim_steps: 30
  scale: 10
  upscale_strength: 0.25
  upscale_steps: 30
  upscale_overlap: 98
subtitles: False
illustrations: False
narrations: False
voice: train-dotrice
